### ISSUE TITLE
effect of target in data generating on inference

### ISSUE THREAD

**Issue by mikeaalv** [NiklasPfister/CausalKinetiX-R#2]
I'm checking reaction(target) 3 as example, which should be related to 1 and 2. 

The block of code with target different in simulation and inference:

```
simulation.obj<-generate.data.maillard(target=1,
                                       env=rep(1:3,5),
                                       L=15,
                                       seed=5,
                                       par.noise=list(noise.sd=1))
D <- simulation.obj$simulated.data#nx(L*d); n:exp*rep; L: #timepoints; d: #X
time <- simulation.obj$time
env <- simulation.obj$env#exp*rep
target <- simulation.obj$target
## Fit data using CausalKinetiX
ck.fit <- CausalKinetiX(D, time, env, 3,
                        pars=list(expsize=1,
                                  average.reps=TRUE))#
# variable ranking (here the true parent is variable 4)
print(ck.fit$ranking)
score=ck.fit[["model.scores"]]
ck.fit[["models"]][which(score==min(score))]
print(min(score))
print(ck.fit[["variable.scores"]][[1]])
```

Return

```
> print(ck.fit$ranking)
 [1] 10  3  7  9  4  6  5  1  2  8 11
> score=ck.fit[["model.scores"]]
> ck.fit[["models"]][which(score==min(score))]
[[1]]
[[1]][[1]]
[1] 3

[[1]][[2]]
[1] 7
```
The result seems quite different from correct result.

The block of code with target the same in simulation and inference:

```
simulation.obj<-generate.data.maillard(target=3,
                                       env=rep(1:3,5),
                                       L=15,
                                       seed=5,
                                       par.noise=list(noise.sd=1))
D <- simulation.obj$simulated.data#nx(L*d); n:exp*rep; L: #timepoints; d: #X
time <- simulation.obj$time
env <- simulation.obj$env#exp*rep
target <- simulation.obj$target
## Fit data using CausalKinetiX
ck.fit <- CausalKinetiX(D, time, env, 3,
                        pars=list(expsize=1,
                                  average.reps=TRUE))#
# variable ranking (here the true parent is variable 4)
print(ck.fit$ranking)
score=ck.fit[["model.scores"]]
ck.fit[["models"]][which(score==min(score))]
print(min(score))
print(ck.fit[["variable.scores"]][[1]])
```

Return

```
> print(ck.fit$ranking)
 [1]  2  3  8  1  4  6  7  9 10 11  5
> score=ck.fit[["model.scores"]]
> ck.fit[["models"]][which(score==min(score))]
[[1]]
[[1]][[1]]
[1] 1

[[1]][[2]]
[1] 2
```

The result is pretty good but should the target in simulation has big effect on inference? I checked the code for `generate.data.maillard` and it seems `target` affect how `intervention` is done. So, I did this:

```
simulation.obj<-generate.data.maillard(target=3,
                                       env=rep(1:3,5),
                                       L=15,
                                       seed=5,intervention='initial',
                                       par.noise=list(noise.sd=1))
D <- simulation.obj$simulated.data#nx(L*d); n:exp*rep; L: #timepoints; d: #X
time <- simulation.obj$time
env <- simulation.obj$env#exp*rep
target <- simulation.obj$target
## Fit data using CausalKinetiX
ck.fit <- CausalKinetiX(D, time, env, 3,
                        pars=list(expsize=1,
                                  average.reps=TRUE))#
# variable ranking (here the true parent is variable 4)
print(ck.fit$ranking)
score=ck.fit[["model.scores"]]
ck.fit[["models"]][which(score==min(score))]
print(min(score))
print(ck.fit[["variable.scores"]][[1]])
```

Return another different result:

```
> print(ck.fit$ranking)
 [1]  2  5  3  4  6  9  7  8  1 10 11
> score=ck.fit[["model.scores"]]
> ck.fit[["models"]][which(score==min(score))]
[[1]]
[[1]][[1]]
[1] 5

[[1]][[2]]
[1] 9
```

Can you help check what's the problem here?

Thank you.

Best.
Yue

**Comment by NiklasPfister** [comment]
Thanks for you interest in CausalKinetiX.

I think there are two issues here:

1) if you use the wrong target (in your case target 1) together with the default type of interventions ("initial_blockreactions") this will result in violations of the invariance assumption of the "true" target that you use later on (target 3). Since it can happen that one of the interventions sets terms in the equation of variable 3 to zero. This is what is producing the behavior that you are observing.
-> Note that if you use (intervention="initial"), you do not need to worry about such violations. And the target used in the simulation is irrelevant.

2) Using interventions="initial" only intervenes by changing the initial values of a random set of variables. While this in all cases preserves the invariance assumption, it also does not modify the structure as strongly as would happen by changing a rate constant. Therefore you generally need slightly more environments to get identifiability in this case. You could for example use env=rep(1:5, 5), which should give you a quite good result. (Note also that even though you do not have full identifiability with these (random) 3 environments you are already seeing models containing variable 2 to be ranked higher).

Let me know if that answers your questions.

Best,
Niklas.

**Comment by mikeaalv** [comment]
These are great explanations. Thank you very much. 

I think in real world experiments, the second case is more common: the target feature are at least with some differences in initial values for different conditions. Assumption on no changes on initial value of the target feature might not be satisfied. Is there any argument to let `generate.data.maillard` simulate all features 'equally' (possible changes in initial value) including the target one?

**Comment by NiklasPfister** [comment]
Changes on the initial values of the target feature are fine. In our framework we only assume the dynamics of the target remains invariant (i.e., the differential equation).

The function generate.data.maillard generates data according to the Maillard reaction. We therefore only change the initial values of variables 1, 2 and 10 the remaining variables are kept at zero. If I understood the biology correctly this would be the general experimental setup. So if intervention="inital" each environment (experiment) is generated by drawing random initial values of variables 1, 2 and 10 (regardless of the target).

Hope that helps!

**Comment by mikeaalv** [comment]
Thank you very much. This is pretty clear
